# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/Code/Other/vivado/cource_design/design1/design1.srcs/sources_1/ip/rom_1024x32b/rom_1024x32b.xci
# IP: The module: 'rom_1024x32b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Code/Other/vivado/cource_design/design1/design1.srcs/sources_1/ip/rom_1024x32b/rom_1024x32b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_1024x32b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/Code/Other/vivado/cource_design/design1/design1.srcs/sources_1/ip/rom_1024x32b/rom_1024x32b.xci
# IP: The module: 'rom_1024x32b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Code/Other/vivado/cource_design/design1/design1.srcs/sources_1/ip/rom_1024x32b/rom_1024x32b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_1024x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
